baseURL = "https://inspacare.com"
title = "Inspacare | Innovative medical glove dispensers"
theme = "ion"
languageCode = "en-US"
enableRobotsTXT = true

[params]
  author = "Victor Ocnarescu"
  fonts = "https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,800&display=swap"
  sitename = "Inspacare"
  description = "Inspacare introduces Glovesafe, an innovative glove dispenser. Reduces waste and contamination of gloves inadvertently removed. Improves safety"
  image = "/images/inspacare-wallpaper.jpg"
  favicon = "favicon.ico"
  analytics = "UA-154808408-1"
  fontAwesome = true
  headingFont = "'Nunito Sans', sans-serif"
  bodyFont = "'Nunito Sans', sans-serif"
  primaryColor = "#007b85"
  secondaryColor = "#4252b1"

[menu]
  [[menu.main]]
    name = "About us"
    url = "/#who-we-are"
    weight = 100
  [[menu.main]]
    name = "The problem"
    url = "/#the-problem"
    weight = 110
  [[menu.main]]
    name = "Logo"
    url = "/"
    weight = 120
  [[menu.main]]
    name = "Our solution"
    url = "/#our-solution"
    weight = 120
  [[menu.main]]
    name = "Order now"
    url = "/#order-now"
    weight = 130
    identifier = "button"
