backend:
  name: git-gateway
media_folder: static/images
public_folder: /images
logo_url: /images/inspacare-logo-admin.png
collections:
  - name: homepage
    label: Homepage sections
    editor:
      preview: false
    files:
      - name: the-facts
        label: The facts
        file: content/the-facts.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: image
          - name: body
            label: Body
            widget: markdown
      - name: who-we-are
        label: Who we are
        file: content/who-we-are.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: image
          - name: body
            label: Body
            widget: markdown
      - name: the-benefits
        label: The benefits
        file: content/the-benefits.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: image
          - name: body
            label: Body
            widget: markdown
      - name: the-problem
        label: The problem
        file: content/the-problem.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: image
          - name: icon
            label: Font Awesome Icon
            widget: string
          - name: body
            label: Body
            widget: markdown
      - name: the-solution
        label: The solution
        file: content/the-solution.md
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: image
          - name: icon
            label: Font Awesome Icon
            widget: string
          - name: body
            label: Body
            widget: markdown
  - name: testimonials
    label: Testimonials
    folder: content/testimonials
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Company
        name: company
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: settings
        label: Update your website settings by clicking here
        file: config.toml
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: object
            name: params
            label: Params
            required: true
            hint: Site parameters
            fields:
              - widget: string
                name: sitename
                label: Title for SEO purposes
              - widget: string
                name: description
                label: Description for SEO purposes
              - widget: string
                name: analytics
                label: Google Analytics tracking code
              - widget: boolean
                name: fontAwesome
                label: Use Font Awesome icons?
  - name: menu
    label: Menus
    editor:
      preview: false
    files:
      - name: menu
        label: Update your website menu by clicking here
        file: config.toml
        fields:
          - widget: object
            name: menu
            label: Site Menus
            required: false
            hint: Menu items not related to a specific page
            fields:
              - widget: list
                name: main
                label: Main menu
                required: false
                hint: List of items for Main menu
                fields:
                  - widget: string
                    name: name
                    label: Menu text
                    required: true
                  - widget: string
                    name: url
                    label: Menu link
                    required: true
                  - widget: number
                    name: weight
                    label: Menu weight
                    required: true
                    hint: >-
                      A menu item is more important (placed more to the left)
                      if its weight is smaller
