backend:
  name: git-gateway
media_folder: static/images
public_folder: /images
# logo_url: /images/inspacare-logo-dark.png
collections:
  - name: testimonials # Used in routes, e.g., /admin/collections/blog
    label: Testimonials # Used in the UI
    folder: content/testimonials # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: Company
        name: company
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: config
    label: Global Site Config
    files:
      - name: config
        label: Global Site Config
        file: config.toml
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: object
            name: params
            label: Params
            required: true
            hint: Site parameters
            fields:
              - widget: string
                name: primaryColor
                label: Primary Color
                required: false
                hint: Primary color of the website
